# See https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
keys:
  - &gf 5790bfc5f6b75631632ef4cbe994f2b92898c272
  - &griffin 1ae7caa6ce078ff1ae5b75a4ec11630a3a86b3d2
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *gf
  - path_regex: secrets/griffin/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *gf
      - *griffin
