# See https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
keys:
  - &gf age1spkek869g8xscxqakuv8yw0ee8kwan803sk4lkxqqh9ywrdzvgtqsfvwwr
creation_rules:
  - path_regex: secret/[^/]+\.(yml|yaml|json|env|ini)$
    key_groups:
    - age:
      - *gf
