FROM gemini-cli-sandbox # nixos/nix
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y nix
RUN echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
RUN echo 'if [ -z "$HAS_ENTERED_NIX_DEVELOP" ]; then \
            export HAS_ENTERED_NIX_DEVELOP=1; \
            exec nix develop; \
          fi' >> /etc/bash.bashrc && \
    echo 'if [ -z "$HAS_ENTERED_NIX_DEVELOP" ]; then \
            export HAS_ENTERED_NIX_DEVELOP=1; \
            exec nix develop; \
          fi' >> /root/.bashrc
# CMD ["/bin/sh", "-c", "sleep infinity"]
