# FROM nixos/nix:latest
FROM us-docker.pkg.dev/gemini-code-dev/gemini-cli/sandbox:0.33.1

USER root
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y direnv fd-find ripgrep sd xz-utils
RUN mkdir --mode 755 --parents /home/node
RUN chown node:users /home/node
# RUN echo 'if [ -z "$NIX_DEV_ENTERED" ]; then' >> /etc/bashrc
# RUN echo '  export NIX_DEV_ENTERED=1;' >> /etc/bashrc
# RUN echo '  exec nix develop;' >> /etc/bashrc
# RUN echo 'fi' >> /etc/bashrc

USER node
ENV USER=node
# ENV HOME=/home/node

# RUN curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install | sh -s -- --no-daemon
# RUN mkdir --parents --verbose $HOME/.cache/host-nix
# RUN mkdir --parents --verbose $HOME/.config/nix
# RUN echo "experimental-features = nix-command flakes" >> $HOME/.config/nix/nix.conf
# RUN echo "substituters = local?root=$HOME/.cache/host-nix https://cache.nixos.org" >> $HOME/.config/nix/nix.conf
# RUN echo "require-sigs = false" >> $HOME/.config/nix/nix.conf
# ENV PATH="$HOME/.nix-profile/bin:$PATH"
# RUN echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf

RUN echo 'if [ -z "$NIX_DEV_ENTERED" ]; then' >> $HOME/.bashrc
RUN echo '  export NIX_DEV_ENTERED=1;' >> $HOME/.bashrc
RUN echo '  exec nix develop;' >> $HOME/.bashrc
RUN echo 'fi' >> $HOME/.bashrc
