example_key: ENC[AES256_GCM,data:Xihmyic6rNe1k+/h7Q==,iv:znuRLgc1aIfg7K24Hy2wtu9Pv2yEhswW1zBrVGPo5I0=,tag:ewAWzvHF5wYWb+PN3GvEKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1spkek869g8xscxqakuv8yw0ee8kwan803sk4lkxqqh9ywrdzvgtqsfvwwr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMFh5ano4dzVKcjZxdU9E
            WjhRazhMd2Z1WVY4Ris4STJXT2N6QS9IT1hVCkdmTm9vVDVvZForK2RTcHp5R280
            SllxOVdyR3dlZVJ1angweFE2L2Z5N00KLS0tIE9LMmFoK2hJQ1MzL0VQMCt0bTAv
            SERiREVldS9JOHEwYmtXZGpLK1BFYWsKE97I9MlWDzSl2oIrXSYqekfE0DI8NVyY
            9ZaO3yrKg7bCFf3DA3hQ/uXghL09WVyg5PlIZ9iLVcaAxHNKsHlqHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T18:18:42Z"
    mac: ENC[AES256_GCM,data:/72cPWyF4HLVGkYhN16bfIuLIqvPiqie13DhSOhPN9LFJhzWM7LiKQFDwfzwWhGOzU+weu4N9KAdWAi5KN/T9YsQ0x5GefdDbafX8w59CrqRcbuDHLrS6+gTduuSkJ8OQgGhLUlv8Rg6OKrhLKJaMUlot+kg7LJNHYxxFmpbrIc=,iv:qDjOSF/2uSfysqP/Mc5Jvi6+uGewBVyiKgzVVIiRTgc=,tag:BJaKuzBR4IRyYtpNJWP5WA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
