hello: ENC[AES256_GCM,data:tC5ZO5WBV4XSpwxCSLIg4qrvGm1V+u6esvelyIMFi6kKUwcH0lsAv72+sw9UdA==,iv:BSLNShvMd3bkdzFcz4LXxgSjNd8SPVoNVHISjzhgtGQ=,tag:e12K2jl8rVOL7GbWtjwOpA==,type:str]
example_key: ENC[AES256_GCM,data:Xihmyic6rNe1k+/h7Q==,iv:znuRLgc1aIfg7K24Hy2wtu9Pv2yEhswW1zBrVGPo5I0=,tag:ewAWzvHF5wYWb+PN3GvEKA==,type:str]
example_array:
    - ENC[AES256_GCM,data:EBvRMnTclMyqSALKKDE=,iv:YTyn793hKV+mTaaP4JyDSWNAVJ1KwJoBpSOvyMicfIY=,tag:V6or2EbhmGU4Xxl8OPaAHg==,type:str]
    - ENC[AES256_GCM,data:FjwLJppJDWelhm+4ARE=,iv:CH0CxnBDNp6UHrAF5LeZzMFJI14GGWeaGH6aDLMI1PU=,tag:QdK94/+72ItOkP9FgQCX6w==,type:str]
example_number: ENC[AES256_GCM,data:tNFjPtvqegjrhg==,iv:QOWzSSxR+W5XvqXqH6KYJCoBbHykvCAwbkprMlHwRgE=,tag:9AqnALQ0obIMofHkgjFcgg==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:lbnRTQ==,iv:Qx1Ul8N5McdEKdwfTN5Fb2bkps9FxW6V4lLn65t2AXs=,tag:3OIzHRbIakmva1VJ87GQ6Q==,type:bool]
    - ENC[AES256_GCM,data:scGtAg0=,iv:Iky6zOW+P0C+LXSYn0NeJT1F/5/SoMDMmS+vdM3uim0=,tag:kuPu/jV/5HRzn/0QB1aoGA==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1spkek869g8xscxqakuv8yw0ee8kwan803sk4lkxqqh9ywrdzvgtqsfvwwr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMFh5ano4dzVKcjZxdU9E
            WjhRazhMd2Z1WVY4Ris4STJXT2N6QS9IT1hVCkdmTm9vVDVvZForK2RTcHp5R280
            SllxOVdyR3dlZVJ1angweFE2L2Z5N00KLS0tIE9LMmFoK2hJQ1MzL0VQMCt0bTAv
            SERiREVldS9JOHEwYmtXZGpLK1BFYWsKE97I9MlWDzSl2oIrXSYqekfE0DI8NVyY
            9ZaO3yrKg7bCFf3DA3hQ/uXghL09WVyg5PlIZ9iLVcaAxHNKsHlqHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T16:40:28Z"
    mac: ENC[AES256_GCM,data:wOEUOVexJxpwXjXJKrnPwOZJLpGlLvxM173zf4RB1q8FR2Q/TJzlCgArEVEmddfPKyVTuvnGZLPBUYHoPt2oD+17nXOsr2cVjGTD+fQFWXvvEMIKA/ZTXC/kHfTOHBoTm8o6RsPPJNebMALMqTle7u8uxKkOOi6j9KVK8osKnM0=,iv:0t0Ts4GVac95ORe/Gpt5dpWCvRRhvu8aYnt9mH5FoYQ=,tag:KE8zQ3dqhZK2lA9j1HiR3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
