Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |lv|
    lv.cpus = "1"
    lv.memory = "256"
  end

  # Inline shell example
  # config.vm.provision :shell, inline: <<-SHELL
  #   uname -a
  # SHELL

  config.vm.define "alpine" do |cfg|
    cfg.vm.box = "generic/alpine319" # Alpine 3.19 (2024 version)
    cfg.vm.hostname = "alpine"
    cfg.vm.provision :docker
    cfg.vm.provision :shell, path: "apk.sh"
    # cfg.vm.network :private_network, ip: "192.168.100.10"
  end

  config.vm.define "fedora" do |cfg|
    cfg.vm.box = "generic/fedora39" # Fedora 39 (early 2024 version)
    cfg.vm.hostname = "fedora"
    cfg.vm.provision :docker
    cfg.vm.provision :shell, path: "dnf.sh"
    # cfg.vm.network :private_network, ip: "192.168.100.10"
  end

  config.vm.define "alma" do |cfg|
    cfg.vm.box = "almalinux/9" # Alma Linux 9 (late 2023 version)
    cfg.vm.hostname = "alma"
    cfg.vm.provision :shell, path: "dnf.sh"
    cfg.vm.provider :libvirt do |lv|
      lv.cpus = "2"
      lv.memory = "1024"
    end
  end

  config.vm.define "debian" do |cfg|
    cfg.vm.box = "debian/bookworm64" # Debian 12 (2023 version)
    cfg.vm.hostname = "debian"
    cfg.vm.provision :docker
    cfg.vm.provision :shell, path: "apt.sh"
    # cfg.vm.network :private_network, ip: "192.168.100.10"
  end

  # config.vm.define "rhel" do |cfg|
  #   cfg.vm.box = "generic/rhel9" # RHEL 9 (late 2023 version)
  #   cfg.vm.hostname = "rhel"
  #   cfg.vm.provision :shell, path: "dnf.sh"
  # end
end
